"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.models.agent_run_citation import (
    AgentRunCitation,
)


class AgentRunGrounding(object):
    """Implementation of the 'AgentRunGrounding' model.

    Citations for one field of `output.structured`.

    Attributes:
        citations (List[AgentRunCitation]): Citations supporting this field's value.
        field (str): Dot-notation path into the structured output, e.g.
            "companies.0.ceo".
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "citations": "citations",
        "field": "field",
    }

    _optionals = [
        "citations",
        "field",
    ]

    def __init__(
        self,
        citations=APIHelper.SKIP,
        field=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AgentRunGrounding instance."""
        # Initialize members of the class
        if citations is not APIHelper.SKIP:
            self.citations = citations
        if field is not APIHelper.SKIP:
            self.field = field

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        citations = None
        if dictionary.get("citations") is not None:
            citations = [
                AgentRunCitation.from_dictionary(x)
                    for x in dictionary.get("citations")
            ]
        else:
            citations = APIHelper.SKIP
        field =\
            dictionary.get("field")\
            if dictionary.get("field")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(citations,
                   field,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _citations=(
            self.citations
            if hasattr(self, "citations")
            else None
        )
        _field=(
            self.field
            if hasattr(self, "field")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"citations={_citations!r}, "
            f"field={_field!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _citations=(
            self.citations
            if hasattr(self, "citations")
            else None
        )
        _field=(
            self.field
            if hasattr(self, "field")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"citations={_citations!s}, "
            f"field={_field!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
