"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class AgentRunStopReason(object):
    """Implementation of the 'AgentRunStopReason' enum.

    Why a run stopped. `budget_reached` pairs with `completed` when the output
    so far is usable and with `failed` when it is not.

    Attributes:
        FINISHED: The enum member of type str.
        BUDGET_REACHED: The enum member of type str.
        TIMEOUT: The enum member of type str.
        CANCELLED: The enum member of type str.
        INVALID_OUTPUT: The enum member of type str.
        INTERNAL_ERROR: The enum member of type str.

    """

    FINISHED = "finished"

    BUDGET_REACHED = "budget_reached"

    TIMEOUT = "timeout"

    CANCELLED = "cancelled"

    INVALID_OUTPUT = "invalid_output"

    INTERNAL_ERROR = "internal_error"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
