"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper


class AgentRunRequest(object):
    """Implementation of the 'AgentRunRequest' model.

    The request a run was created with.

    Attributes:
        effort (str): The effort level the run executes at: the request's `effort`,
            or the default level when it named none.
        output_schema (Any): The request's `output_schema`, when one was given. On
            gRPC the object is JSON-encoded.
        query (str): The natural-language question.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "effort": "effort",
        "output_schema": "output_schema",
        "query": "query",
    }

    _optionals = [
        "effort",
        "output_schema",
        "query",
    ]

    _nullables = [
        "effort",
        "output_schema",
    ]

    def __init__(
        self,
        effort=APIHelper.SKIP,
        output_schema=APIHelper.SKIP,
        query=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AgentRunRequest instance."""
        # Initialize members of the class
        if effort is not APIHelper.SKIP:
            self.effort = effort
        if output_schema is not APIHelper.SKIP:
            self.output_schema = output_schema
        if query is not APIHelper.SKIP:
            self.query = query

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        effort =\
            dictionary.get("effort")\
            if "effort" in dictionary.keys()\
                else APIHelper.SKIP
        output_schema =\
            dictionary.get("output_schema")\
            if "output_schema" in dictionary.keys()\
                else APIHelper.SKIP
        query =\
            dictionary.get("query")\
            if dictionary.get("query")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(effort,
                   output_schema,
                   query,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _effort=(
            self.effort
            if hasattr(self, "effort")
            else None
        )
        _output_schema=(
            self.output_schema
            if hasattr(self, "output_schema")
            else None
        )
        _query=(
            self.query
            if hasattr(self, "query")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"effort={_effort!r}, "
            f"output_schema={_output_schema!r}, "
            f"query={_query!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _effort=(
            self.effort
            if hasattr(self, "effort")
            else None
        )
        _output_schema=(
            self.output_schema
            if hasattr(self, "output_schema")
            else None
        )
        _query=(
            self.query
            if hasattr(self, "query")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"effort={_effort!s}, "
            f"output_schema={_output_schema!s}, "
            f"query={_query!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
