"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.models.agent_run_output_2 import (
    AgentRunOutput2,
)
from seltzapi.models.agent_run_request_2 import (
    AgentRunRequest2,
)


class AgentRun(object):
    """Implementation of the 'AgentRun' model.

    An agent run.

    Attributes:
        completed_at (str): When the run reached a terminal state. Unset until then.
        created_at (str): When the run was created, as an ISO 8601 timestamp.
        id (str): Unique run id.
        object (str): Object type, always "agent.run".
        output (AgentRunOutput2): The model property of type AgentRunOutput2.
        request (AgentRunRequest2): The model property of type AgentRunRequest2.
        started_at (str): When the run started. Unset while pending.
        status (AgentRunStatus2): The model property of type AgentRunStatus2.
        stop_reason (AgentRunStopReason2): The model property of type
            AgentRunStopReason2.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "completed_at": "completed_at",
        "created_at": "created_at",
        "id": "id",
        "object": "object",
        "output": "output",
        "request": "request",
        "started_at": "started_at",
        "status": "status",
        "stop_reason": "stop_reason",
    }

    _optionals = [
        "completed_at",
        "created_at",
        "id",
        "object",
        "output",
        "request",
        "started_at",
        "status",
        "stop_reason",
    ]

    _nullables = [
        "completed_at",
        "output",
        "request",
        "started_at",
        "stop_reason",
    ]

    def __init__(
        self,
        completed_at=APIHelper.SKIP,
        created_at=APIHelper.SKIP,
        id=APIHelper.SKIP,
        object=APIHelper.SKIP,
        output=APIHelper.SKIP,
        request=APIHelper.SKIP,
        started_at=APIHelper.SKIP,
        status="pending",
        stop_reason=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AgentRun instance."""
        # Initialize members of the class
        if completed_at is not APIHelper.SKIP:
            self.completed_at = completed_at
        if created_at is not APIHelper.SKIP:
            self.created_at = created_at
        if id is not APIHelper.SKIP:
            self.id = id
        if object is not APIHelper.SKIP:
            self.object = object
        if output is not APIHelper.SKIP:
            self.output = output
        if request is not APIHelper.SKIP:
            self.request = request
        if started_at is not APIHelper.SKIP:
            self.started_at = started_at
        self.status = status
        if stop_reason is not APIHelper.SKIP:
            self.stop_reason = stop_reason

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        completed_at =\
            dictionary.get("completed_at")\
            if "completed_at" in dictionary.keys()\
                else APIHelper.SKIP
        created_at =\
            dictionary.get("created_at")\
            if dictionary.get("created_at")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        object =\
            dictionary.get("object")\
            if dictionary.get("object")\
                else APIHelper.SKIP
        if "output" in dictionary.keys():
            output =\
                AgentRunOutput2.from_dictionary(
                dictionary.get("output"))\
                if dictionary.get("output") else None
        else:
            output = APIHelper.SKIP
        if "request" in dictionary.keys():
            request =\
                AgentRunRequest2.from_dictionary(
                dictionary.get("request"))\
                if dictionary.get("request") else None
        else:
            request = APIHelper.SKIP
        started_at =\
            dictionary.get("started_at")\
            if "started_at" in dictionary.keys()\
                else APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else "pending"
        stop_reason =\
            dictionary.get("stop_reason")\
            if "stop_reason" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(completed_at,
                   created_at,
                   id,
                   object,
                   output,
                   request,
                   started_at,
                   status,
                   stop_reason,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _completed_at=(
            self.completed_at
            if hasattr(self, "completed_at")
            else None
        )
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _object=(
            self.object
            if hasattr(self, "object")
            else None
        )
        _output=(
            self.output
            if hasattr(self, "output")
            else None
        )
        _request=(
            self.request
            if hasattr(self, "request")
            else None
        )
        _started_at=(
            self.started_at
            if hasattr(self, "started_at")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _stop_reason=(
            self.stop_reason
            if hasattr(self, "stop_reason")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"completed_at={_completed_at!r}, "
            f"created_at={_created_at!r}, "
            f"id={_id!r}, "
            f"object={_object!r}, "
            f"output={_output!r}, "
            f"request={_request!r}, "
            f"started_at={_started_at!r}, "
            f"status={_status!r}, "
            f"stop_reason={_stop_reason!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _completed_at=(
            self.completed_at
            if hasattr(self, "completed_at")
            else None
        )
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _object=(
            self.object
            if hasattr(self, "object")
            else None
        )
        _output=(
            self.output
            if hasattr(self, "output")
            else None
        )
        _request=(
            self.request
            if hasattr(self, "request")
            else None
        )
        _started_at=(
            self.started_at
            if hasattr(self, "started_at")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _stop_reason=(
            self.stop_reason
            if hasattr(self, "stop_reason")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"completed_at={_completed_at!s}, "
            f"created_at={_created_at!s}, "
            f"id={_id!s}, "
            f"object={_object!s}, "
            f"output={_output!s}, "
            f"request={_request!s}, "
            f"started_at={_started_at!s}, "
            f"status={_status!s}, "
            f"stop_reason={_stop_reason!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
