"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.models.agent_run_grounding import (
    AgentRunGrounding,
)
from seltzapi.models.agent_run_source import (
    AgentRunSource,
)


class AgentRunOutput2(object):
    """Implementation of the 'AgentRunOutput2' model.

    The run's output. Its members are unset until the run completes.

    Attributes:
        grounding (List[AgentRunGrounding]): Per-field citations for `structured`.
            Empty when there is no structured output.
        sources (List[AgentRunSource]): The sources cited by `text` or `grounding`,
            numbered in order of first citation.
        structured (Any): Structured result shaped by the request's `output_schema`.
            Unset when the request had none. Fields that could not be grounded are
            expected to be null. On gRPC the object is JSON-encoded.
        text (str): Cited markdown report. Inline `\[n\]` markers cite the entry of
            `sources` whose `id` is `n`.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "grounding": "grounding",
        "sources": "sources",
        "structured": "structured",
        "text": "text",
    }

    _optionals = [
        "grounding",
        "sources",
        "structured",
        "text",
    ]

    _nullables = [
        "structured",
        "text",
    ]

    def __init__(
        self,
        grounding=APIHelper.SKIP,
        sources=APIHelper.SKIP,
        structured=APIHelper.SKIP,
        text=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AgentRunOutput2 instance."""
        # Initialize members of the class
        if grounding is not APIHelper.SKIP:
            self.grounding = grounding
        if sources is not APIHelper.SKIP:
            self.sources = sources
        if structured is not APIHelper.SKIP:
            self.structured = structured
        if text is not APIHelper.SKIP:
            self.text = text

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        grounding = None
        if dictionary.get("grounding") is not None:
            grounding = [
                AgentRunGrounding.from_dictionary(x)
                    for x in dictionary.get("grounding")
            ]
        else:
            grounding = APIHelper.SKIP
        sources = None
        if dictionary.get("sources") is not None:
            sources = [
                AgentRunSource.from_dictionary(x)
                    for x in dictionary.get("sources")
            ]
        else:
            sources = APIHelper.SKIP
        structured =\
            dictionary.get("structured")\
            if "structured" in dictionary.keys()\
                else APIHelper.SKIP
        text =\
            dictionary.get("text")\
            if "text" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(grounding,
                   sources,
                   structured,
                   text,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _grounding=(
            self.grounding
            if hasattr(self, "grounding")
            else None
        )
        _sources=(
            self.sources
            if hasattr(self, "sources")
            else None
        )
        _structured=(
            self.structured
            if hasattr(self, "structured")
            else None
        )
        _text=(
            self.text
            if hasattr(self, "text")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"grounding={_grounding!r}, "
            f"sources={_sources!r}, "
            f"structured={_structured!r}, "
            f"text={_text!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _grounding=(
            self.grounding
            if hasattr(self, "grounding")
            else None
        )
        _sources=(
            self.sources
            if hasattr(self, "sources")
            else None
        )
        _structured=(
            self.structured
            if hasattr(self, "structured")
            else None
        )
        _text=(
            self.text
            if hasattr(self, "text")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"grounding={_grounding!s}, "
            f"sources={_sources!s}, "
            f"structured={_structured!s}, "
            f"text={_text!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
