"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper


class AnswerHttpRequest(object):
    """Implementation of the 'AnswerHttpRequest' model.

    JSON request body for `POST /v1/answer`.

    Attributes:
        api_key (str): API key. Either this or the `x-api-key` header must be
            supplied; the header takes precedence.
        include_content (bool): When true, citations carry the document content text.
            Default false.
        model (str): Selects the answer tier, which determines behavior and billing.
            Omitted resolves to the default tier. Independent of `scope`; the
            response shape is unchanged.
        query (str): The natural-language question.
        response_format (Any): Optional `OpenAI` `response_format` object (`{"type":
            "text" | "json_object" | "json_schema", ...}`), accepted as raw JSON
            exactly like `/v1/chat/completions`. Under a structured type no inline
            citations are added, so the answer stays schema-valid; a malformed value
            is a `400` before billing. Omitted leaves the answer as Markdown prose.
            Applies at every tier.
        scope (str): Restricts the grounding search to one scope.  Currently
            available:  - `news` - `wikipedia` - `people` - `companies`  Omitted,
            empty or whitespace-only searches the default scope.
        stream (bool): When true, stream the answer as OpenAI-mimic SSE chunks.
            Default false.
        system_prompt (str): Steers how the answer is presented — tone, voice,
            format. It is subordinate to the grounding and citation rules, which stay
            in force. That precedence is instructional, not a sandbox. Omitted, empty
            or whitespace-only leaves the presentation unchanged. Applies at every
            tier and composes with `response_format`. At most 8 KiB of UTF-8; a
            longer value is a `400` before billing.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "query": "query",
        "api_key": "api_key",
        "include_content": "include_content",
        "model": "model",
        "response_format": "response_format",
        "scope": "scope",
        "stream": "stream",
        "system_prompt": "system_prompt",
    }

    _optionals = [
        "api_key",
        "include_content",
        "model",
        "response_format",
        "scope",
        "stream",
        "system_prompt",
    ]

    _nullables = [
        "api_key",
        "model",
        "scope",
        "system_prompt",
    ]

    def __init__(
        self,
        query=None,
        api_key=APIHelper.SKIP,
        include_content=APIHelper.SKIP,
        model=APIHelper.SKIP,
        response_format=APIHelper.SKIP,
        scope=APIHelper.SKIP,
        stream=APIHelper.SKIP,
        system_prompt=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AnswerHttpRequest instance."""
        # Initialize members of the class
        if api_key is not APIHelper.SKIP:
            self.api_key = api_key
        if include_content is not APIHelper.SKIP:
            self.include_content = include_content
        if model is not APIHelper.SKIP:
            self.model = model
        self.query = query
        if response_format is not APIHelper.SKIP:
            self.response_format = response_format
        if scope is not APIHelper.SKIP:
            self.scope = scope
        if stream is not APIHelper.SKIP:
            self.stream = stream
        if system_prompt is not APIHelper.SKIP:
            self.system_prompt = system_prompt

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        query =\
            dictionary.get("query")\
            if dictionary.get("query")\
                else None
        api_key =\
            dictionary.get("api_key")\
            if "api_key" in dictionary.keys()\
                else APIHelper.SKIP
        include_content =\
            dictionary.get("include_content")\
            if "include_content" in dictionary.keys()\
                else APIHelper.SKIP
        model =\
            dictionary.get("model")\
            if "model" in dictionary.keys()\
                else APIHelper.SKIP
        response_format =\
            dictionary.get("response_format")\
            if dictionary.get("response_format")\
                else APIHelper.SKIP
        scope =\
            dictionary.get("scope")\
            if "scope" in dictionary.keys()\
                else APIHelper.SKIP
        stream =\
            dictionary.get("stream")\
            if "stream" in dictionary.keys()\
                else APIHelper.SKIP
        system_prompt =\
            dictionary.get("system_prompt")\
            if "system_prompt" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(query,
                   api_key,
                   include_content,
                   model,
                   response_format,
                   scope,
                   stream,
                   system_prompt,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _api_key=(
            self.api_key
            if hasattr(self, "api_key")
            else None
        )
        _include_content=(
            self.include_content
            if hasattr(self, "include_content")
            else None
        )
        _model=(
            self.model
            if hasattr(self, "model")
            else None
        )
        _query=self.query
        _response_format=(
            self.response_format
            if hasattr(self, "response_format")
            else None
        )
        _scope=(
            self.scope
            if hasattr(self, "scope")
            else None
        )
        _stream=(
            self.stream
            if hasattr(self, "stream")
            else None
        )
        _system_prompt=(
            self.system_prompt
            if hasattr(self, "system_prompt")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"api_key={_api_key!r}, "
            f"include_content={_include_content!r}, "
            f"model={_model!r}, "
            f"query={_query!r}, "
            f"response_format={_response_format!r}, "
            f"scope={_scope!r}, "
            f"stream={_stream!r}, "
            f"system_prompt={_system_prompt!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _api_key=(
            self.api_key
            if hasattr(self, "api_key")
            else None
        )
        _include_content=(
            self.include_content
            if hasattr(self, "include_content")
            else None
        )
        _model=(
            self.model
            if hasattr(self, "model")
            else None
        )
        _query=self.query
        _response_format=(
            self.response_format
            if hasattr(self, "response_format")
            else None
        )
        _scope=(
            self.scope
            if hasattr(self, "scope")
            else None
        )
        _stream=(
            self.stream
            if hasattr(self, "stream")
            else None
        )
        _system_prompt=(
            self.system_prompt
            if hasattr(self, "system_prompt")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"api_key={_api_key!s}, "
            f"include_content={_include_content!s}, "
            f"model={_model!s}, "
            f"query={_query!s}, "
            f"response_format={_response_format!s}, "
            f"scope={_scope!s}, "
            f"stream={_stream!s}, "
            f"system_prompt={_system_prompt!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
