"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.models.http_citation import HttpCitation


class AnswerHttpResponse(object):
    """Implementation of the 'AnswerHttpResponse' model.

    Buffered JSON response body for `POST /v1/answer`.

    Attributes:
        answer (str): Markdown answer text. Inline citations follow the form `text
            ([Source Name](url))`.
        citations (List[HttpCitation]): The sources the answer was grounded in. Every
            source the answer was given is returned, whether or not the text cites it.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "answer": "answer",
        "citations": "citations",
    }

    def __init__(
        self,
        answer=None,
        citations=None,
        additional_properties=None):
        """Initialize a AnswerHttpResponse instance."""
        # Initialize members of the class
        self.answer = answer
        self.citations = citations

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        answer =\
            dictionary.get("answer")\
            if dictionary.get("answer")\
                else None
        citations = None
        if dictionary.get("citations") is not None:
            citations = [
                HttpCitation.from_dictionary(x)
                    for x in dictionary.get("citations")
            ]

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(answer,
                   citations,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _answer=self.answer
        _citations=self.citations
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"answer={_answer!r}, "
            f"citations={_citations!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _answer=self.answer
        _citations=self.citations
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"answer={_answer!s}, "
            f"citations={_citations!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
