"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper


class ContentOptions(object):
    """Implementation of the 'ContentOptions' model.

    The ceiling on the content returned.
    The ceiling is an upper bound; the response carries at most what is specified
    here.
    The service may hold callers to a tighter bound than the range below. A larger
    request is then served at that bound rather than refused, which still carries at
    most what was specified. Only a value outside the range below is rejected.

    Attributes:
        max_characters_per_result (int): Ceiling on the characters of any single
            result's content.  Counts Unicode code points -- Rust `char`, Python
            `len(s)`, JavaScript `\[...s\].length`.  Defaults to 20000, accepted
            range 100-1000000.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "max_characters_per_result": "max_characters_per_result",
    }

    _optionals = [
        "max_characters_per_result",
    ]

    _nullables = [
        "max_characters_per_result",
    ]

    def __init__(
        self,
        max_characters_per_result=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ContentOptions instance."""
        # Initialize members of the class
        if max_characters_per_result is not APIHelper.SKIP:
            self.max_characters_per_result = max_characters_per_result

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        max_characters_per_result =\
            dictionary.get("max_characters_per_result")\
            if "max_characters_per_result" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(max_characters_per_result,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _max_characters_per_result=(
            self.max_characters_per_result
            if hasattr(self, "max_characters_per_result")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"max_characters_per_result={_max_characters_per_result!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _max_characters_per_result=(
            self.max_characters_per_result
            if hasattr(self, "max_characters_per_result")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"max_characters_per_result={_max_characters_per_result!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
