"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper


class CreateAgentRunRequest(object):
    """Implementation of the 'CreateAgentRunRequest' model.

    Attributes:
        api_key (str): The API key, on gRPC requests. REST reads the `x-api-key`
            header instead.
        effort (str): Effort level: how much research the run may do, and its price.
            One of the configured level names (e.g. `low`, `medium`, `high`, `max`).
            Omitted = the default level.
        output_schema (Any): Optional OpenAI-style `response_format` object
            requesting structured output: `{"type": "text" | "json_object" |
            "json_schema", ...}`, with `name` / `schema` / `strict` for type
            `json_schema`. A structured type adds `output.structured` and its
            `grounding` alongside the cited text; type `text` is accepted and
            requests no structure. On gRPC the object is JSON-encoded.
        query (str): The natural-language question. Instructions inside the query are
            followed.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "api_key": "api_key",
        "effort": "effort",
        "output_schema": "output_schema",
        "query": "query",
    }

    _optionals = [
        "api_key",
        "effort",
        "output_schema",
        "query",
    ]

    _nullables = [
        "api_key",
        "effort",
        "output_schema",
    ]

    def __init__(
        self,
        api_key=APIHelper.SKIP,
        effort=APIHelper.SKIP,
        output_schema=APIHelper.SKIP,
        query=APIHelper.SKIP):
        """Initialize a CreateAgentRunRequest instance."""
        # Initialize members of the class
        if api_key is not APIHelper.SKIP:
            self.api_key = api_key
        if effort is not APIHelper.SKIP:
            self.effort = effort
        if output_schema is not APIHelper.SKIP:
            self.output_schema = output_schema
        if query is not APIHelper.SKIP:
            self.query = query

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        api_key =\
            dictionary.get("api_key")\
            if "api_key" in dictionary.keys()\
                else APIHelper.SKIP
        effort =\
            dictionary.get("effort")\
            if "effort" in dictionary.keys()\
                else APIHelper.SKIP
        output_schema =\
            dictionary.get("output_schema")\
            if "output_schema" in dictionary.keys()\
                else APIHelper.SKIP
        query =\
            dictionary.get("query")\
            if dictionary.get("query")\
                else APIHelper.SKIP

        # Return an object of this model
        return cls(api_key,
                   effort,
                   output_schema,
                   query)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _api_key=(
            self.api_key
            if hasattr(self, "api_key")
            else None
        )
        _effort=(
            self.effort
            if hasattr(self, "effort")
            else None
        )
        _output_schema=(
            self.output_schema
            if hasattr(self, "output_schema")
            else None
        )
        _query=(
            self.query
            if hasattr(self, "query")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"api_key={_api_key!r}, "
            f"effort={_effort!r}, "
            f"output_schema={_output_schema!r}, "
            f"query={_query!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _api_key=(
            self.api_key
            if hasattr(self, "api_key")
            else None
        )
        _effort=(
            self.effort
            if hasattr(self, "effort")
            else None
        )
        _output_schema=(
            self.output_schema
            if hasattr(self, "output_schema")
            else None
        )
        _query=(
            self.query
            if hasattr(self, "query")
            else None
        )
        return (
            f"{self.__class__.__name__}("
            f"api_key={_api_key!s}, "
            f"effort={_effort!s}, "
            f"output_schema={_output_schema!s}, "
            f"query={_query!s}, "
            f")"
        )
