"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.models.search_request import SearchRequest
from seltzapi.models.webhook import Webhook


class CreateMonitorRequest(object):
    """Implementation of the 'CreateMonitorRequest' model.

    Attributes:
        cadence (str): The model property of type str.
        api_key (str): The model property of type str.
        name (str): Unique per org among live monitors; a deleted monitor's name
            becomes available again. At most 512 bytes of UTF-8.
        search_requests (List[SearchRequest]): At least one, at most 1000. Every
            request runs on every run. A request with an `api_key` set, a blank
            `query`, or a body identical to another in the list is rejected.
        status (MonitorStatus2): The model property of type MonitorStatus2.
        webhook (Webhook): The model property of type Webhook.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "cadence": "cadence",
        "api_key": "api_key",
        "name": "name",
        "search_requests": "search_requests",
        "status": "status",
        "webhook": "webhook",
    }

    _optionals = [
        "api_key",
        "name",
        "search_requests",
        "status",
        "webhook",
    ]

    _nullables = [
        "api_key",
        "webhook",
    ]

    def __init__(
        self,
        cadence=None,
        api_key=APIHelper.SKIP,
        name=APIHelper.SKIP,
        search_requests=APIHelper.SKIP,
        status=APIHelper.SKIP,
        webhook=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CreateMonitorRequest instance."""
        # Initialize members of the class
        self.cadence = cadence
        if api_key is not APIHelper.SKIP:
            self.api_key = api_key
        if name is not APIHelper.SKIP:
            self.name = name
        if search_requests is not APIHelper.SKIP:
            self.search_requests = search_requests
        if status is not APIHelper.SKIP:
            self.status = status
        if webhook is not APIHelper.SKIP:
            self.webhook = webhook

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        cadence =\
            dictionary.get("cadence")\
            if dictionary.get("cadence")\
                else None
        api_key =\
            dictionary.get("api_key")\
            if "api_key" in dictionary.keys()\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        search_requests = None
        if dictionary.get("search_requests") is not None:
            search_requests = [
                SearchRequest.from_dictionary(x)
                    for x in dictionary.get("search_requests")
            ]
        else:
            search_requests = APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else APIHelper.SKIP
        if "webhook" in dictionary.keys():
            webhook =\
                Webhook.from_dictionary(
                dictionary.get("webhook"))\
                if dictionary.get("webhook") else None
        else:
            webhook = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(cadence,
                   api_key,
                   name,
                   search_requests,
                   status,
                   webhook,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _cadence=self.cadence
        _api_key=(
            self.api_key
            if hasattr(self, "api_key")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _search_requests=(
            self.search_requests
            if hasattr(self, "search_requests")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _webhook=(
            self.webhook
            if hasattr(self, "webhook")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"cadence={_cadence!r}, "
            f"api_key={_api_key!r}, "
            f"name={_name!r}, "
            f"search_requests={_search_requests!r}, "
            f"status={_status!r}, "
            f"webhook={_webhook!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _cadence=self.cadence
        _api_key=(
            self.api_key
            if hasattr(self, "api_key")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _search_requests=(
            self.search_requests
            if hasattr(self, "search_requests")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _webhook=(
            self.webhook
            if hasattr(self, "webhook")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"cadence={_cadence!s}, "
            f"api_key={_api_key!s}, "
            f"name={_name!s}, "
            f"search_requests={_search_requests!s}, "
            f"status={_status!s}, "
            f"webhook={_webhook!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
