"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.models.monitor import Monitor


class CreateMonitorResponse(object):
    """Implementation of the 'CreateMonitorResponse' model.

    Attributes:
        monitor (Monitor): The model property of type Monitor.
        webhook_secret (str): Returned once, at create, and never again. Issued
            whether or not the create supplied a webhook, so keep it.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "monitor": "monitor",
        "webhook_secret": "webhook_secret",
    }

    _optionals = [
        "monitor",
        "webhook_secret",
    ]

    _nullables = [
        "monitor",
    ]

    def __init__(
        self,
        monitor=APIHelper.SKIP,
        webhook_secret=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CreateMonitorResponse instance."""
        # Initialize members of the class
        if monitor is not APIHelper.SKIP:
            self.monitor = monitor
        if webhook_secret is not APIHelper.SKIP:
            self.webhook_secret = webhook_secret

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        if "monitor" in dictionary.keys():
            monitor =\
                Monitor.from_dictionary(
                dictionary.get("monitor"))\
                if dictionary.get("monitor") else None
        else:
            monitor = APIHelper.SKIP
        webhook_secret =\
            dictionary.get("webhook_secret")\
            if dictionary.get("webhook_secret")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(monitor,
                   webhook_secret,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _monitor=(
            self.monitor
            if hasattr(self, "monitor")
            else None
        )
        _webhook_secret=(
            self.webhook_secret
            if hasattr(self, "webhook_secret")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"monitor={_monitor!r}, "
            f"webhook_secret={_webhook_secret!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _monitor=(
            self.monitor
            if hasattr(self, "monitor")
            else None
        )
        _webhook_secret=(
            self.webhook_secret
            if hasattr(self, "webhook_secret")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"monitor={_monitor!s}, "
            f"webhook_secret={_webhook_secret!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
