"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.models.snippet import Snippet


class Document(object):
    """Implementation of the 'Document' model.

    A single search result.
    `url` and `published_date` are returned without being asked for, and either
    may still be absent for a document that carries no such value. The remaining
    members are populated only when `SearchRequest.fields` asked for them.

    Attributes:
        content (str): The model property of type str.
        published_date (str): Publication date as ISO 8601 string (e.g.
            "2024-03-15T00:00:00Z")
        snippets (List[Snippet]): The document's highest-scoring snippets, in the
            order they appear in the document.  Populated when `fields.snippets` is
            selected and passages are available; empty otherwise.
        url (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "content": "content",
        "published_date": "published_date",
        "snippets": "snippets",
        "url": "url",
    }

    _optionals = [
        "content",
        "published_date",
        "snippets",
        "url",
    ]

    _nullables = [
        "content",
        "published_date",
        "url",
    ]

    def __init__(
        self,
        content=APIHelper.SKIP,
        published_date=APIHelper.SKIP,
        snippets=APIHelper.SKIP,
        url=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Document instance."""
        # Initialize members of the class
        if content is not APIHelper.SKIP:
            self.content = content
        if published_date is not APIHelper.SKIP:
            self.published_date = published_date
        if snippets is not APIHelper.SKIP:
            self.snippets = snippets
        if url is not APIHelper.SKIP:
            self.url = url

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        content =\
            dictionary.get("content")\
            if "content" in dictionary.keys()\
                else APIHelper.SKIP
        published_date =\
            dictionary.get("published_date")\
            if "published_date" in dictionary.keys()\
                else APIHelper.SKIP
        snippets = None
        if dictionary.get("snippets") is not None:
            snippets = [
                Snippet.from_dictionary(x)
                    for x in dictionary.get("snippets")
            ]
        else:
            snippets = APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if "url" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(content,
                   published_date,
                   snippets,
                   url,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _content=(
            self.content
            if hasattr(self, "content")
            else None
        )
        _published_date=(
            self.published_date
            if hasattr(self, "published_date")
            else None
        )
        _snippets=(
            self.snippets
            if hasattr(self, "snippets")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"content={_content!r}, "
            f"published_date={_published_date!r}, "
            f"snippets={_snippets!r}, "
            f"url={_url!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _content=(
            self.content
            if hasattr(self, "content")
            else None
        )
        _published_date=(
            self.published_date
            if hasattr(self, "published_date")
            else None
        )
        _snippets=(
            self.snippets
            if hasattr(self, "snippets")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"content={_content!s}, "
            f"published_date={_published_date!s}, "
            f"snippets={_snippets!s}, "
            f"url={_url!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
