"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.models.fetch_result import FetchResult


class FetchResponse(object):
    """Implementation of the 'FetchResponse' model.

    One result per requested URL.

    Attributes:
        results (List[FetchResult]): One entry per entry in `FetchRequest.urls`,
            successful or not, in the order the URLs were requested.  Correlate on
            `FetchResult.requested_url` rather than on position.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "results": "results",
    }

    _optionals = [
        "results",
    ]

    def __init__(
        self,
        results=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a FetchResponse instance."""
        # Initialize members of the class
        if results is not APIHelper.SKIP:
            self.results = results

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        results = None
        if dictionary.get("results") is not None:
            results = [
                FetchResult.from_dictionary(x)
                    for x in dictionary.get("results")
            ]
        else:
            results = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(results,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _results=(
            self.results
            if hasattr(self, "results")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"results={_results!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _results=(
            self.results
            if hasattr(self, "results")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"results={_results!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
