"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper


class FetchError1(object):
    """Implementation of the 'FetchError1' model.

    Why the fetch failed. Set when `status` is the error status, unset
    otherwise.

    Attributes:
        code (str): A stable, machine-readable reason. A client must treat an
            unrecognized code as a generic failure rather than rejecting the result.
            Documented codes:  "invalid_url"              -- not a parseable absolute
            URL. "unsupported_scheme"       -- parseable, but not `http` or `https`.
            "url_not_accessible"       -- DNS, connection, TLS, or navigation failure
            reaching the origin, or a host this service does not fetch. "timeout"
            -- the fetch did not finish within `timeout_ms`.
            "unsupported_content_type" -- the document is not an HTML page. PDFs,
            images, archives, and other binaries are out of scope. Refused from the
            URL before the fetch, or from the media type the origin declared after
            it. "extraction_failed"        -- the page was fetched, but no requested
            format could be produced from it. "upstream_error"           -- the fetch
            path itself failed. Ours, not the URL's.
        message (str): A human-readable explanation. Always set when this message is
            present: `FetchError` itself is optional on the result, so an absent
            error is absent whole, and there is no state where a failure arrives
            without a reason. For operators and logs. Never parse it -- branch on
            `code`. The wording of any given message may change at any time.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "code": "code",
        "message": "message",
    }

    _optionals = [
        "code",
        "message",
    ]

    def __init__(
        self,
        code=APIHelper.SKIP,
        message=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a FetchError1 instance."""
        # Initialize members of the class
        if code is not APIHelper.SKIP:
            self.code = code
        if message is not APIHelper.SKIP:
            self.message = message

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        code =\
            dictionary.get("code")\
            if dictionary.get("code")\
                else APIHelper.SKIP
        message =\
            dictionary.get("message")\
            if dictionary.get("message")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(code,
                   message,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _code=(
            self.code
            if hasattr(self, "code")
            else None
        )
        _message=(
            self.message
            if hasattr(self, "message")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"code={_code!r}, "
            f"message={_message!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _code=(
            self.code
            if hasattr(self, "code")
            else None
        )
        _message=(
            self.message
            if hasattr(self, "message")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"code={_code!s}, "
            f"message={_message!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
