"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper


class FetchRequest(object):
    """Implementation of the 'FetchRequest' model.

    Attributes:
        api_key (str): API key to access the service. Either this or the `x-api-key`
            header must be supplied on the HTTP surface; the header takes precedence
            and is the documented path. On gRPC this field is the only carrier.  Each
            URL that comes back with the OK status is billed. A URL that comes back
            with an error is not. The call is refused up front unless the balance
            covers the whole batch.
        formats (List[str]): Representations to return, as documented format names.
            Omitted, or sent empty, means `\["markdown"\]` -- a repeated field
            carries no presence, so the two are the same request and neither means
            "no formats".  Documented names:  "markdown" -- the main content as
            Markdown, boilerplate removed.  An unrecognized name is rejected.
        tier (str): The service tier, which selects the price. Send `"pro"`. Unset
            resolves to `"pro"`.  An unrecognized value is rejected rather than
            defaulted, because the value selects a price. The name is matched exactly.
        timeout_ms (int): Wall-clock budget for one URL, in milliseconds.  Applies to
            each URL, not to the batch. A URL that exceeds the budget gets
            `error.code = "timeout"`; the others in the same request are unaffected.
            Unset means 75000, which is also the maximum; a larger value is served as
            75000, and a value below 1000 is served as 1000.
        urls (List[str]): The URLs to fetch. At least one, at most 20.  An empty
            list, more than 20 entries, a duplicate entry, a blank or padded entry,
            or an entry over 2048 bytes is rejected before any billing -- duplicates
            because `FetchResult.requested_url` is the correlation key and a repeated
            key is ambiguous.  Everything else is reported inside a `200` as that
            URL's error result: a value that is not an absolute `http` or `https`
            URL, a host that does not resolve or that this service will not fetch, an
            origin that refuses, and a document that is not an HTML page.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "api_key": "api_key",
        "formats": "formats",
        "tier": "tier",
        "timeout_ms": "timeout_ms",
        "urls": "urls",
    }

    _optionals = [
        "api_key",
        "formats",
        "tier",
        "timeout_ms",
        "urls",
    ]

    _nullables = [
        "api_key",
        "tier",
        "timeout_ms",
    ]

    def __init__(
        self,
        api_key=APIHelper.SKIP,
        formats=None,
        tier=APIHelper.SKIP,
        timeout_ms=APIHelper.SKIP,
        urls=None,
        additional_properties=None):
        """Initialize a FetchRequest instance."""
        # Initialize members of the class
        if api_key is not APIHelper.SKIP:
            self.api_key = api_key
        self.formats = formats
        if tier is not APIHelper.SKIP:
            self.tier = tier
        if timeout_ms is not APIHelper.SKIP:
            self.timeout_ms = timeout_ms
        self.urls = urls

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        api_key =\
            dictionary.get("api_key")\
            if "api_key" in dictionary.keys()\
                else APIHelper.SKIP
        formats =\
            dictionary.get("formats")\
            if dictionary.get("formats")\
                else None
        tier =\
            dictionary.get("tier")\
            if "tier" in dictionary.keys()\
                else APIHelper.SKIP
        timeout_ms =\
            dictionary.get("timeout_ms")\
            if "timeout_ms" in dictionary.keys()\
                else APIHelper.SKIP
        urls =\
            dictionary.get("urls")\
            if dictionary.get("urls")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(api_key,
                   formats,
                   tier,
                   timeout_ms,
                   urls,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _api_key=(
            self.api_key
            if hasattr(self, "api_key")
            else None
        )
        _formats=(
            self.formats
            if hasattr(self, "formats")
            else None
        )
        _tier=(
            self.tier
            if hasattr(self, "tier")
            else None
        )
        _timeout_ms=(
            self.timeout_ms
            if hasattr(self, "timeout_ms")
            else None
        )
        _urls=(
            self.urls
            if hasattr(self, "urls")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"api_key={_api_key!r}, "
            f"formats={_formats!r}, "
            f"tier={_tier!r}, "
            f"timeout_ms={_timeout_ms!r}, "
            f"urls={_urls!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _api_key=(
            self.api_key
            if hasattr(self, "api_key")
            else None
        )
        _formats=(
            self.formats
            if hasattr(self, "formats")
            else None
        )
        _tier=(
            self.tier
            if hasattr(self, "tier")
            else None
        )
        _timeout_ms=(
            self.timeout_ms
            if hasattr(self, "timeout_ms")
            else None
        )
        _urls=(
            self.urls
            if hasattr(self, "urls")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"api_key={_api_key!s}, "
            f"formats={_formats!s}, "
            f"tier={_tier!s}, "
            f"timeout_ms={_timeout_ms!s}, "
            f"urls={_urls!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
