"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class FetchStatus2(object):
    """Implementation of the 'FetchStatus2' enum.

    Whether this result carries content.
    Branch on this field, never on whether a given content field is present: a
    format the page could not produce is unset on an otherwise successful
    result, so "markdown is absent" does not mean "the fetch failed".
    A failed fetch is still HTTP 200, with the error status on the result.

    Attributes:
        OK: The enum member of type str.
        ERROR: The enum member of type str.

    """

    OK = "ok"

    ERROR = "error"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
