"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper


class Fields2(object):
    """Implementation of the 'Fields2' model.

    Which selectable members of `Document` to populate.
    If absent, defaults to `{content: true}`, which returns content under the
    default ceiling stated on `ContentOptions`.

    Attributes:
        content (bool | ContentOptions | None): Emit `Document.content`. Unset is
            true.
        snippets (bool | SnippetOptions | None): Emit `Document.snippets`. Unset is
            false.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "content": "content",
        "snippets": "snippets",
    }

    _optionals = [
        "content",
        "snippets",
    ]

    def __init__(
        self,
        content=APIHelper.SKIP,
        snippets=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Fields2 instance."""
        # Initialize members of the class
        if content is not APIHelper.SKIP:
            self.content = content
        if snippets is not APIHelper.SKIP:
            self.snippets = snippets

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from seltzapi.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        content = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("Fields2Content"),
            dictionary.get("content"),
            False)\
            if dictionary.get("content") is not None\
            else APIHelper.SKIP
        snippets = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("Fields2Snippets"),
            dictionary.get("snippets"),
            False)\
            if dictionary.get("snippets") is not None\
            else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(content,
                   snippets,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _content=(
            self.content
            if hasattr(self, "content")
            else None
        )
        _snippets=(
            self.snippets
            if hasattr(self, "snippets")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"content={_content!r}, "
            f"snippets={_snippets!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _content=(
            self.content
            if hasattr(self, "content")
            else None
        )
        _snippets=(
            self.snippets
            if hasattr(self, "snippets")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"content={_content!s}, "
            f"snippets={_snippets!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
