"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.models.run import Run


class GetRunResponse(object):
    """Implementation of the 'GetRunResponse' model.

    Attributes:
        run (Run): The model property of type Run.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "run": "run",
    }

    _optionals = [
        "run",
    ]

    _nullables = [
        "run",
    ]

    def __init__(
        self,
        run=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a GetRunResponse instance."""
        # Initialize members of the class
        if run is not APIHelper.SKIP:
            self.run = run

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        if "run" in dictionary.keys():
            run =\
                Run.from_dictionary(
                dictionary.get("run"))\
                if dictionary.get("run") else None
        else:
            run = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(run,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _run=(
            self.run
            if hasattr(self, "run")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"run={_run!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _run=(
            self.run
            if hasattr(self, "run")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"run={_run!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
