"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.models.monitor import Monitor


class GetMonitorResponse(object):
    """Implementation of the 'GetMonitorResponse' model.

    Attributes:
        monitor (Monitor): The model property of type Monitor.
        run_state (RunState2): The model property of type RunState2.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "run_state": "run_state",
        "monitor": "monitor",
    }

    _optionals = [
        "monitor",
    ]

    _nullables = [
        "monitor",
    ]

    def __init__(
        self,
        run_state="idle",
        monitor=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a GetMonitorResponse instance."""
        # Initialize members of the class
        if monitor is not APIHelper.SKIP:
            self.monitor = monitor
        self.run_state = run_state

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        run_state =\
            dictionary.get("run_state")\
            if dictionary.get("run_state")\
                else "idle"
        if "monitor" in dictionary.keys():
            monitor =\
                Monitor.from_dictionary(
                dictionary.get("monitor"))\
                if dictionary.get("monitor") else None
        else:
            monitor = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(run_state,
                   monitor,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _monitor=(
            self.monitor
            if hasattr(self, "monitor")
            else None
        )
        _run_state=self.run_state
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"monitor={_monitor!r}, "
            f"run_state={_run_state!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _monitor=(
            self.monitor
            if hasattr(self, "monitor")
            else None
        )
        _run_state=self.run_state
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"monitor={_monitor!s}, "
            f"run_state={_run_state!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
