"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper


class HttpCitation(object):
    """Implementation of the 'HttpCitation' model.

    HTTP-shape citation. Mirrors the `Citation` proto.

    Attributes:
        content (str): Document content text (only when `include_content = true`).
        url (str): URL of the source document.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "url": "url",
        "content": "content",
    }

    _optionals = [
        "content",
    ]

    _nullables = [
        "content",
    ]

    def __init__(
        self,
        url=None,
        content=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a HttpCitation instance."""
        # Initialize members of the class
        if content is not APIHelper.SKIP:
            self.content = content
        self.url = url

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else None
        content =\
            dictionary.get("content")\
            if "content" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(url,
                   content,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _content=(
            self.content
            if hasattr(self, "content")
            else None
        )
        _url=self.url
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"content={_content!r}, "
            f"url={_url!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _content=(
            self.content
            if hasattr(self, "content")
            else None
        )
        _url=self.url
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"content={_content!s}, "
            f"url={_url!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
