"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.models.run_request import RunRequest


class ListRunRequestsResponse(object):
    """Implementation of the 'ListRunRequestsResponse' model.

    Attributes:
        requests (List[RunRequest]): Ordered by request_id.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "requests": "requests",
    }

    _optionals = [
        "requests",
    ]

    def __init__(
        self,
        requests=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ListRunRequestsResponse instance."""
        # Initialize members of the class
        if requests is not APIHelper.SKIP:
            self.requests = requests

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        requests = None
        if dictionary.get("requests") is not None:
            requests = [
                RunRequest.from_dictionary(x)
                    for x in dictionary.get("requests")
            ]
        else:
            requests = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(requests,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _requests=(
            self.requests
            if hasattr(self, "requests")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"requests={_requests!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _requests=(
            self.requests
            if hasattr(self, "requests")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"requests={_requests!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
