"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.models.agent_run import AgentRun


class ListAgentRunsResponse(object):
    """Implementation of the 'ListAgentRunsResponse' model.

    List-runs response: one page of runs.

    Attributes:
        next (str): Cursor to the next page. Unset on the last page.
        runs (List[AgentRun]): The page's runs, newest first.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "next": "next",
        "runs": "runs",
    }

    _optionals = [
        "next",
        "runs",
    ]

    _nullables = [
        "next",
    ]

    def __init__(
        self,
        next=APIHelper.SKIP,
        runs=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ListAgentRunsResponse instance."""
        # Initialize members of the class
        if next is not APIHelper.SKIP:
            self.next = next
        if runs is not APIHelper.SKIP:
            self.runs = runs

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        next =\
            dictionary.get("next")\
            if "next" in dictionary.keys()\
                else APIHelper.SKIP
        runs = None
        if dictionary.get("runs") is not None:
            runs = [
                AgentRun.from_dictionary(x)
                    for x in dictionary.get("runs")
            ]
        else:
            runs = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(next,
                   runs,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _next=(
            self.next
            if hasattr(self, "next")
            else None
        )
        _runs=(
            self.runs
            if hasattr(self, "runs")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"next={_next!r}, "
            f"runs={_runs!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _next=(
            self.next
            if hasattr(self, "next")
            else None
        )
        _runs=(
            self.runs
            if hasattr(self, "runs")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"next={_next!s}, "
            f"runs={_runs!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
