"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.models.monitor import Monitor


class ListMonitorsResponse(object):
    """Implementation of the 'ListMonitorsResponse' model.

    Attributes:
        has_more (bool): True when limit or the byte budget cut the page short. Page
            forward with before = monitors\[last\].monitor_id.
        monitors (List[Monitor]): Newest first. A short page is normal: a page ends
            at limit or at a byte budget, whichever binds first. A monitor carries
            its whole request list, so a count alone cannot bound the response.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "has_more": "has_more",
        "monitors": "monitors",
    }

    _optionals = [
        "has_more",
        "monitors",
    ]

    def __init__(
        self,
        has_more=False,
        monitors=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ListMonitorsResponse instance."""
        # Initialize members of the class
        self.has_more = has_more
        if monitors is not APIHelper.SKIP:
            self.monitors = monitors

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        has_more =\
            dictionary.get("has_more")\
            if dictionary.get("has_more")\
                else False
        monitors = None
        if dictionary.get("monitors") is not None:
            monitors = [
                Monitor.from_dictionary(x)
                    for x in dictionary.get("monitors")
            ]
        else:
            monitors = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(has_more,
                   monitors,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _has_more=(
            self.has_more
            if hasattr(self, "has_more")
            else None
        )
        _monitors=(
            self.monitors
            if hasattr(self, "monitors")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"has_more={_has_more!r}, "
            f"monitors={_monitors!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _has_more=(
            self.has_more
            if hasattr(self, "has_more")
            else None
        )
        _monitors=(
            self.monitors
            if hasattr(self, "monitors")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"has_more={_has_more!s}, "
            f"monitors={_monitors!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
