"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.models.run import Run


class ListRunsResponse(object):
    """Implementation of the 'ListRunsResponse' model.

    Attributes:
        has_more (bool): True when limit cut the page short.
        runs (List[Run]): Newest first by default, so \[0\] is the latest run. Page
            back with before = runs\[last\].run_id; pass sort = SORT_ORDER_ASC to
            walk forward instead, and page with since = runs\[last\].run_id.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "has_more": "has_more",
        "runs": "runs",
    }

    _optionals = [
        "has_more",
        "runs",
    ]

    def __init__(
        self,
        has_more=False,
        runs=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ListRunsResponse instance."""
        # Initialize members of the class
        self.has_more = has_more
        if runs is not APIHelper.SKIP:
            self.runs = runs

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        has_more =\
            dictionary.get("has_more")\
            if dictionary.get("has_more")\
                else False
        runs = None
        if dictionary.get("runs") is not None:
            runs = [
                Run.from_dictionary(x)
                    for x in dictionary.get("runs")
            ]
        else:
            runs = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(has_more,
                   runs,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _has_more=(
            self.has_more
            if hasattr(self, "has_more")
            else None
        )
        _runs=(
            self.runs
            if hasattr(self, "runs")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"has_more={_has_more!r}, "
            f"runs={_runs!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _has_more=(
            self.has_more
            if hasattr(self, "has_more")
            else None
        )
        _runs=(
            self.runs
            if hasattr(self, "runs")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"has_more={_has_more!s}, "
            f"runs={_runs!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
