"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class MonitorStatus(object):
    """Implementation of the 'MonitorStatus' enum.

    A monitor's lifecycle state.
    `active` is scheduled and running. `paused` runs nothing and keeps its
    records and its record of what it has already delivered. Only those two can
    be set through the API; `disabled` and `deleted` are set by Seltz.

    Attributes:
        ACTIVE: The enum member of type str.
        PAUSED: The enum member of type str.
        DISABLED: The enum member of type str.
        DELETED: The enum member of type str.

    """

    ACTIVE = "active"

    PAUSED = "paused"

    DISABLED = "disabled"

    DELETED = "deleted"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
