"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class MonitorStatus2(object):
    """Implementation of the 'MonitorStatus2' enum.

    Set to `paused` to create the monitor without starting it. Only `active`
    and `paused` are accepted. Defaults to `active`.

    Attributes:
        ACTIVE: The enum member of type str.
        PAUSED: The enum member of type str.
        DISABLED: The enum member of type str.
        DELETED: The enum member of type str.

    """

    ACTIVE = "active"

    PAUSED = "paused"

    DISABLED = "disabled"

    DELETED = "deleted"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
