"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.models.monitor_search_request import (
    MonitorSearchRequest,
)
from seltzapi.models.webhook import Webhook


class Monitor(object):
    """Implementation of the 'Monitor' model.

    Attributes:
        cadence (str): The model property of type str.
        created_at (str): The model property of type str.
        monitor_id (str): The model property of type str.
        name (str): The model property of type str.
        search_requests (List[MonitorSearchRequest]): The model property of type
            List[MonitorSearchRequest].
        status (MonitorStatus): The model property of type MonitorStatus.
        updated_at (str): The model property of type str.
        webhook (Webhook): The model property of type Webhook.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "cadence": "cadence",
        "status": "status",
        "created_at": "created_at",
        "monitor_id": "monitor_id",
        "name": "name",
        "search_requests": "search_requests",
        "updated_at": "updated_at",
        "webhook": "webhook",
    }

    _optionals = [
        "created_at",
        "monitor_id",
        "name",
        "search_requests",
        "updated_at",
        "webhook",
    ]

    _nullables = [
        "created_at",
        "updated_at",
        "webhook",
    ]

    def __init__(
        self,
        cadence=None,
        status="active",
        created_at=APIHelper.SKIP,
        monitor_id=APIHelper.SKIP,
        name=APIHelper.SKIP,
        search_requests=APIHelper.SKIP,
        updated_at=APIHelper.SKIP,
        webhook=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Monitor instance."""
        # Initialize members of the class
        self.cadence = cadence
        if created_at is not APIHelper.SKIP:
            self.created_at = created_at
        if monitor_id is not APIHelper.SKIP:
            self.monitor_id = monitor_id
        if name is not APIHelper.SKIP:
            self.name = name
        if search_requests is not APIHelper.SKIP:
            self.search_requests = search_requests
        self.status = status
        if updated_at is not APIHelper.SKIP:
            self.updated_at = updated_at
        if webhook is not APIHelper.SKIP:
            self.webhook = webhook

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        cadence =\
            dictionary.get("cadence")\
            if dictionary.get("cadence")\
                else None
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else "active"
        created_at =\
            dictionary.get("created_at")\
            if "created_at" in dictionary.keys()\
                else APIHelper.SKIP
        monitor_id =\
            dictionary.get("monitor_id")\
            if dictionary.get("monitor_id")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        search_requests = None
        if dictionary.get("search_requests") is not None:
            search_requests = [
                MonitorSearchRequest.from_dictionary(x)
                    for x in dictionary.get("search_requests")
            ]
        else:
            search_requests = APIHelper.SKIP
        updated_at =\
            dictionary.get("updated_at")\
            if "updated_at" in dictionary.keys()\
                else APIHelper.SKIP
        if "webhook" in dictionary.keys():
            webhook =\
                Webhook.from_dictionary(
                dictionary.get("webhook"))\
                if dictionary.get("webhook") else None
        else:
            webhook = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(cadence,
                   status,
                   created_at,
                   monitor_id,
                   name,
                   search_requests,
                   updated_at,
                   webhook,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _cadence=self.cadence
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _monitor_id=(
            self.monitor_id
            if hasattr(self, "monitor_id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _search_requests=(
            self.search_requests
            if hasattr(self, "search_requests")
            else None
        )
        _status=self.status
        _updated_at=(
            self.updated_at
            if hasattr(self, "updated_at")
            else None
        )
        _webhook=(
            self.webhook
            if hasattr(self, "webhook")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"cadence={_cadence!r}, "
            f"created_at={_created_at!r}, "
            f"monitor_id={_monitor_id!r}, "
            f"name={_name!r}, "
            f"search_requests={_search_requests!r}, "
            f"status={_status!r}, "
            f"updated_at={_updated_at!r}, "
            f"webhook={_webhook!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _cadence=self.cadence
        _created_at=(
            self.created_at
            if hasattr(self, "created_at")
            else None
        )
        _monitor_id=(
            self.monitor_id
            if hasattr(self, "monitor_id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _search_requests=(
            self.search_requests
            if hasattr(self, "search_requests")
            else None
        )
        _status=self.status
        _updated_at=(
            self.updated_at
            if hasattr(self, "updated_at")
            else None
        )
        _webhook=(
            self.webhook
            if hasattr(self, "webhook")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"cadence={_cadence!s}, "
            f"created_at={_created_at!s}, "
            f"monitor_id={_monitor_id!s}, "
            f"name={_name!s}, "
            f"search_requests={_search_requests!s}, "
            f"status={_status!s}, "
            f"updated_at={_updated_at!s}, "
            f"webhook={_webhook!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
