"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.models.search_request import SearchRequest


class MonitorSearchRequest(object):
    """Implementation of the 'MonitorSearchRequest' model.

    A search request stored on a monitor, with its server-assigned id.

    Attributes:
        consecutive_failures (int): Consecutive failed runs for this request.
        last_success_at (str): The model property of type str.
        request (SearchRequest): The model property of type SearchRequest.
        request_id (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "consecutive_failures": "consecutive_failures",
        "last_success_at": "last_success_at",
        "request": "request",
        "request_id": "request_id",
    }

    _optionals = [
        "consecutive_failures",
        "last_success_at",
        "request",
        "request_id",
    ]

    _nullables = [
        "last_success_at",
        "request",
    ]

    def __init__(
        self,
        consecutive_failures=0,
        last_success_at=APIHelper.SKIP,
        request=APIHelper.SKIP,
        request_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a MonitorSearchRequest instance."""
        # Initialize members of the class
        self.consecutive_failures = consecutive_failures
        if last_success_at is not APIHelper.SKIP:
            self.last_success_at = last_success_at
        if request is not APIHelper.SKIP:
            self.request = request
        if request_id is not APIHelper.SKIP:
            self.request_id = request_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        consecutive_failures =\
            dictionary.get("consecutive_failures")\
            if dictionary.get("consecutive_failures")\
                else 0
        last_success_at =\
            dictionary.get("last_success_at")\
            if "last_success_at" in dictionary.keys()\
                else APIHelper.SKIP
        if "request" in dictionary.keys():
            request =\
                SearchRequest.from_dictionary(
                dictionary.get("request"))\
                if dictionary.get("request") else None
        else:
            request = APIHelper.SKIP
        request_id =\
            dictionary.get("request_id")\
            if dictionary.get("request_id")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(consecutive_failures,
                   last_success_at,
                   request,
                   request_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _consecutive_failures=(
            self.consecutive_failures
            if hasattr(self, "consecutive_failures")
            else None
        )
        _last_success_at=(
            self.last_success_at
            if hasattr(self, "last_success_at")
            else None
        )
        _request=(
            self.request
            if hasattr(self, "request")
            else None
        )
        _request_id=(
            self.request_id
            if hasattr(self, "request_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"consecutive_failures={_consecutive_failures!r}, "
            f"last_success_at={_last_success_at!r}, "
            f"request={_request!r}, "
            f"request_id={_request_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _consecutive_failures=(
            self.consecutive_failures
            if hasattr(self, "consecutive_failures")
            else None
        )
        _last_success_at=(
            self.last_success_at
            if hasattr(self, "last_success_at")
            else None
        )
        _request=(
            self.request
            if hasattr(self, "request")
            else None
        )
        _request_id=(
            self.request_id
            if hasattr(self, "request_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"consecutive_failures={_consecutive_failures!s}, "
            f"last_success_at={_last_success_at!s}, "
            f"request={_request!s}, "
            f"request_id={_request_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
