"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.models.search_record import SearchRecord


class Payload(object):
    """Implementation of the 'Payload' model.

    Attributes:
        search_result (SearchRecord): The model property of type SearchRecord.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "search_result": "search_result",
    }

    def __init__(
        self,
        search_result=None,
        additional_properties=None):
        """Initialize a Payload instance."""
        # Initialize members of the class
        self.search_result = search_result

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        search_result =\
            SearchRecord.from_dictionary(
                dictionary.get("search_result"))\
                if dictionary.get("search_result") else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(search_result,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _search_result=self.search_result
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"search_result={_search_result!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _search_result=self.search_result
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"search_result={_search_result!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
