"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.models.search_record import SearchRecord


class Record(object):
    """Implementation of the 'Record' model.

    Attributes:
        search_result (SearchRecord): The model property of type SearchRecord.
        first_seen_at (str): The model property of type str.
        record_id (str): The model property of type str.
        run_id (str): The model property of type str.
        mtype (RecordType): The model property of type RecordType.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "search_result": "search_result",
        "mtype": "type",
        "first_seen_at": "first_seen_at",
        "record_id": "record_id",
        "run_id": "run_id",
    }

    _optionals = [
        "first_seen_at",
        "record_id",
        "run_id",
    ]

    _nullables = [
        "first_seen_at",
    ]

    def __init__(
        self,
        search_result=None,
        mtype="search_result",
        first_seen_at=APIHelper.SKIP,
        record_id="0",
        run_id="0",
        additional_properties=None):
        """Initialize a Record instance."""
        # Initialize members of the class
        self.search_result = search_result
        if first_seen_at is not APIHelper.SKIP:
            self.first_seen_at = first_seen_at
        self.record_id = record_id
        self.run_id = run_id
        self.mtype = mtype

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        search_result =\
            SearchRecord.from_dictionary(
                dictionary.get("search_result"))\
                if dictionary.get("search_result") else None
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else "search_result"
        first_seen_at =\
            dictionary.get("first_seen_at")\
            if "first_seen_at" in dictionary.keys()\
                else APIHelper.SKIP
        record_id =\
            dictionary.get("record_id")\
            if dictionary.get("record_id")\
                else "0"
        run_id =\
            dictionary.get("run_id")\
            if dictionary.get("run_id")\
                else "0"

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(search_result,
                   mtype,
                   first_seen_at,
                   record_id,
                   run_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _search_result=self.search_result
        _first_seen_at=(
            self.first_seen_at
            if hasattr(self, "first_seen_at")
            else None
        )
        _record_id=(
            self.record_id
            if hasattr(self, "record_id")
            else None
        )
        _run_id=(
            self.run_id
            if hasattr(self, "run_id")
            else None
        )
        _mtype=self.mtype
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"search_result={_search_result!r}, "
            f"first_seen_at={_first_seen_at!r}, "
            f"record_id={_record_id!r}, "
            f"run_id={_run_id!r}, "
            f"mtype={_mtype!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _search_result=self.search_result
        _first_seen_at=(
            self.first_seen_at
            if hasattr(self, "first_seen_at")
            else None
        )
        _record_id=(
            self.record_id
            if hasattr(self, "record_id")
            else None
        )
        _run_id=(
            self.run_id
            if hasattr(self, "run_id")
            else None
        )
        _mtype=self.mtype
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"search_result={_search_result!s}, "
            f"first_seen_at={_first_seen_at!s}, "
            f"record_id={_record_id!s}, "
            f"run_id={_run_id!s}, "
            f"mtype={_mtype!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
