"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper


class Run(object):
    """Implementation of the 'Run' model.

    Attributes:
        completed_at (str): The model property of type str.
        first_record_id (str): The lowest `record_id` this run produced. Records are
            not contiguous; use `record_count` for the count.
        last_record_id (str): The highest `record_id` this run produced. Records are
            not contiguous; use `record_count` for the count.
        monitor_id (str): The model property of type str.
        record_count (int): The model property of type int.
        requests_failed (int): The model property of type int.
        requests_ok (int): The model property of type int.
        requests_total (int): The model property of type int.
        run_id (str): The model property of type str.
        started_at (str): The model property of type str.
        status (RunStatus): The model property of type RunStatus.
        status_reason (str): Prose for a human, empty when completed.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "status": "status",
        "completed_at": "completed_at",
        "first_record_id": "first_record_id",
        "last_record_id": "last_record_id",
        "monitor_id": "monitor_id",
        "record_count": "record_count",
        "requests_failed": "requests_failed",
        "requests_ok": "requests_ok",
        "requests_total": "requests_total",
        "run_id": "run_id",
        "started_at": "started_at",
        "status_reason": "status_reason",
    }

    _optionals = [
        "completed_at",
        "first_record_id",
        "last_record_id",
        "monitor_id",
        "record_count",
        "requests_failed",
        "requests_ok",
        "requests_total",
        "run_id",
        "started_at",
        "status_reason",
    ]

    _nullables = [
        "completed_at",
        "started_at",
    ]

    def __init__(
        self,
        status="completed",
        completed_at=APIHelper.SKIP,
        first_record_id="0",
        last_record_id="0",
        monitor_id=APIHelper.SKIP,
        record_count=0,
        requests_failed=0,
        requests_ok=0,
        requests_total=0,
        run_id="0",
        started_at=APIHelper.SKIP,
        status_reason=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Run instance."""
        # Initialize members of the class
        if completed_at is not APIHelper.SKIP:
            self.completed_at = completed_at
        self.first_record_id = first_record_id
        self.last_record_id = last_record_id
        if monitor_id is not APIHelper.SKIP:
            self.monitor_id = monitor_id
        self.record_count = record_count
        self.requests_failed = requests_failed
        self.requests_ok = requests_ok
        self.requests_total = requests_total
        self.run_id = run_id
        if started_at is not APIHelper.SKIP:
            self.started_at = started_at
        self.status = status
        if status_reason is not APIHelper.SKIP:
            self.status_reason = status_reason

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else "completed"
        completed_at =\
            dictionary.get("completed_at")\
            if "completed_at" in dictionary.keys()\
                else APIHelper.SKIP
        first_record_id =\
            dictionary.get("first_record_id")\
            if dictionary.get("first_record_id")\
                else "0"
        last_record_id =\
            dictionary.get("last_record_id")\
            if dictionary.get("last_record_id")\
                else "0"
        monitor_id =\
            dictionary.get("monitor_id")\
            if dictionary.get("monitor_id")\
                else APIHelper.SKIP
        record_count =\
            dictionary.get("record_count")\
            if dictionary.get("record_count")\
                else 0
        requests_failed =\
            dictionary.get("requests_failed")\
            if dictionary.get("requests_failed")\
                else 0
        requests_ok =\
            dictionary.get("requests_ok")\
            if dictionary.get("requests_ok")\
                else 0
        requests_total =\
            dictionary.get("requests_total")\
            if dictionary.get("requests_total")\
                else 0
        run_id =\
            dictionary.get("run_id")\
            if dictionary.get("run_id")\
                else "0"
        started_at =\
            dictionary.get("started_at")\
            if "started_at" in dictionary.keys()\
                else APIHelper.SKIP
        status_reason =\
            dictionary.get("status_reason")\
            if dictionary.get("status_reason")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(status,
                   completed_at,
                   first_record_id,
                   last_record_id,
                   monitor_id,
                   record_count,
                   requests_failed,
                   requests_ok,
                   requests_total,
                   run_id,
                   started_at,
                   status_reason,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _completed_at=(
            self.completed_at
            if hasattr(self, "completed_at")
            else None
        )
        _first_record_id=(
            self.first_record_id
            if hasattr(self, "first_record_id")
            else None
        )
        _last_record_id=(
            self.last_record_id
            if hasattr(self, "last_record_id")
            else None
        )
        _monitor_id=(
            self.monitor_id
            if hasattr(self, "monitor_id")
            else None
        )
        _record_count=(
            self.record_count
            if hasattr(self, "record_count")
            else None
        )
        _requests_failed=(
            self.requests_failed
            if hasattr(self, "requests_failed")
            else None
        )
        _requests_ok=(
            self.requests_ok
            if hasattr(self, "requests_ok")
            else None
        )
        _requests_total=(
            self.requests_total
            if hasattr(self, "requests_total")
            else None
        )
        _run_id=(
            self.run_id
            if hasattr(self, "run_id")
            else None
        )
        _started_at=(
            self.started_at
            if hasattr(self, "started_at")
            else None
        )
        _status=self.status
        _status_reason=(
            self.status_reason
            if hasattr(self, "status_reason")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"completed_at={_completed_at!r}, "
            f"first_record_id={_first_record_id!r}, "
            f"last_record_id={_last_record_id!r}, "
            f"monitor_id={_monitor_id!r}, "
            f"record_count={_record_count!r}, "
            f"requests_failed={_requests_failed!r}, "
            f"requests_ok={_requests_ok!r}, "
            f"requests_total={_requests_total!r}, "
            f"run_id={_run_id!r}, "
            f"started_at={_started_at!r}, "
            f"status={_status!r}, "
            f"status_reason={_status_reason!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _completed_at=(
            self.completed_at
            if hasattr(self, "completed_at")
            else None
        )
        _first_record_id=(
            self.first_record_id
            if hasattr(self, "first_record_id")
            else None
        )
        _last_record_id=(
            self.last_record_id
            if hasattr(self, "last_record_id")
            else None
        )
        _monitor_id=(
            self.monitor_id
            if hasattr(self, "monitor_id")
            else None
        )
        _record_count=(
            self.record_count
            if hasattr(self, "record_count")
            else None
        )
        _requests_failed=(
            self.requests_failed
            if hasattr(self, "requests_failed")
            else None
        )
        _requests_ok=(
            self.requests_ok
            if hasattr(self, "requests_ok")
            else None
        )
        _requests_total=(
            self.requests_total
            if hasattr(self, "requests_total")
            else None
        )
        _run_id=(
            self.run_id
            if hasattr(self, "run_id")
            else None
        )
        _started_at=(
            self.started_at
            if hasattr(self, "started_at")
            else None
        )
        _status=self.status
        _status_reason=(
            self.status_reason
            if hasattr(self, "status_reason")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"completed_at={_completed_at!s}, "
            f"first_record_id={_first_record_id!s}, "
            f"last_record_id={_last_record_id!s}, "
            f"monitor_id={_monitor_id!s}, "
            f"record_count={_record_count!s}, "
            f"requests_failed={_requests_failed!s}, "
            f"requests_ok={_requests_ok!s}, "
            f"requests_total={_requests_total!s}, "
            f"run_id={_run_id!s}, "
            f"started_at={_started_at!s}, "
            f"status={_status!s}, "
            f"status_reason={_status_reason!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
