"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class RunStatus(object):
    """Implementation of the 'RunStatus' enum.

    A run's outcome.
    `completed` -- every request succeeded. `partial` -- at least one request
    failed after retries and at least one succeeded. `failed` -- no request
    succeeded, and no records. `skipped` -- not attempted and not billed; see
    `status_reason`. Any of them may produce no records.

    Attributes:
        COMPLETED: The enum member of type str.
        PARTIAL: The enum member of type str.
        FAILED: The enum member of type str.
        SKIPPED: The enum member of type str.

    """

    COMPLETED = "completed"

    PARTIAL = "partial"

    FAILED = "failed"

    SKIPPED = "skipped"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
