"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper


class RunRequest(object):
    """Implementation of the 'RunRequest' model.

    One run's outcome for one search request.

    Attributes:
        completed_at (str): The model property of type str.
        new_records (int): The model property of type int.
        reason (str): Why the request failed, empty when it succeeded. Not
            machine-readable.
        request_id (str): The model property of type str.
        results_returned (int): The model property of type int.
        status (RequestStatus): The model property of type RequestStatus.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "status": "status",
        "completed_at": "completed_at",
        "new_records": "new_records",
        "reason": "reason",
        "request_id": "request_id",
        "results_returned": "results_returned",
    }

    _optionals = [
        "completed_at",
        "new_records",
        "reason",
        "request_id",
        "results_returned",
    ]

    _nullables = [
        "completed_at",
    ]

    def __init__(
        self,
        status="ok",
        completed_at=APIHelper.SKIP,
        new_records=0,
        reason=APIHelper.SKIP,
        request_id=APIHelper.SKIP,
        results_returned=0,
        additional_properties=None):
        """Initialize a RunRequest instance."""
        # Initialize members of the class
        if completed_at is not APIHelper.SKIP:
            self.completed_at = completed_at
        self.new_records = new_records
        if reason is not APIHelper.SKIP:
            self.reason = reason
        if request_id is not APIHelper.SKIP:
            self.request_id = request_id
        self.results_returned = results_returned
        self.status = status

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else "ok"
        completed_at =\
            dictionary.get("completed_at")\
            if "completed_at" in dictionary.keys()\
                else APIHelper.SKIP
        new_records =\
            dictionary.get("new_records")\
            if dictionary.get("new_records")\
                else 0
        reason =\
            dictionary.get("reason")\
            if dictionary.get("reason")\
                else APIHelper.SKIP
        request_id =\
            dictionary.get("request_id")\
            if dictionary.get("request_id")\
                else APIHelper.SKIP
        results_returned =\
            dictionary.get("results_returned")\
            if dictionary.get("results_returned")\
                else 0

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(status,
                   completed_at,
                   new_records,
                   reason,
                   request_id,
                   results_returned,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _completed_at=(
            self.completed_at
            if hasattr(self, "completed_at")
            else None
        )
        _new_records=(
            self.new_records
            if hasattr(self, "new_records")
            else None
        )
        _reason=(
            self.reason
            if hasattr(self, "reason")
            else None
        )
        _request_id=(
            self.request_id
            if hasattr(self, "request_id")
            else None
        )
        _results_returned=(
            self.results_returned
            if hasattr(self, "results_returned")
            else None
        )
        _status=self.status
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"completed_at={_completed_at!r}, "
            f"new_records={_new_records!r}, "
            f"reason={_reason!r}, "
            f"request_id={_request_id!r}, "
            f"results_returned={_results_returned!r}, "
            f"status={_status!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _completed_at=(
            self.completed_at
            if hasattr(self, "completed_at")
            else None
        )
        _new_records=(
            self.new_records
            if hasattr(self, "new_records")
            else None
        )
        _reason=(
            self.reason
            if hasattr(self, "reason")
            else None
        )
        _request_id=(
            self.request_id
            if hasattr(self, "request_id")
            else None
        )
        _results_returned=(
            self.results_returned
            if hasattr(self, "results_returned")
            else None
        )
        _status=self.status
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"completed_at={_completed_at!s}, "
            f"new_records={_new_records!s}, "
            f"reason={_reason!s}, "
            f"request_id={_request_id!s}, "
            f"results_returned={_results_returned!s}, "
            f"status={_status!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
