"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class RunState(object):
    """Implementation of the 'RunState' enum.

    Whether a monitor has a run open on it right now.

    Attributes:
        IDLE: The enum member of type str.
        RUNNING: The enum member of type str.
        UNKNOWN: The enum member of type str.

    """

    IDLE = "idle"

    RUNNING = "running"

    UNKNOWN = "unknown"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
