"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper


class Schedule(object):
    """Implementation of the 'Schedule' model.

    Attributes:
        cadence (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "cadence": "cadence",
    }

    def __init__(
        self,
        cadence=None,
        additional_properties=None):
        """Initialize a Schedule instance."""
        # Initialize members of the class
        self.cadence = cadence

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        cadence =\
            dictionary.get("cadence")\
            if dictionary.get("cadence")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(cadence,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _cadence=self.cadence
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"cadence={_cadence!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _cadence=self.cadence
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"cadence={_cadence!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
