"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.models.document import Document


class SearchResponse(object):
    """Implementation of the 'SearchResponse' model.

    Attributes:
        documents (List[Document]): Documents that are most relevant to the query
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "documents": "documents",
    }

    _optionals = [
        "documents",
    ]

    def __init__(
        self,
        documents=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a SearchResponse instance."""
        # Initialize members of the class
        if documents is not APIHelper.SKIP:
            self.documents = documents

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        documents = None
        if dictionary.get("documents") is not None:
            documents = [
                Document.from_dictionary(x)
                    for x in dictionary.get("documents")
            ]
        else:
            documents = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(documents,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _documents=(
            self.documents
            if hasattr(self, "documents")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"documents={_documents!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _documents=(
            self.documents
            if hasattr(self, "documents")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"documents={_documents!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
