"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.models.document import Document
from seltzapi.models.search_request_ref import (
    SearchRequestRef,
)


class SearchRecord(object):
    """Implementation of the 'SearchRecord' model.

    Attributes:
        document (Document): The model property of type Document.
        matched_requests (List[SearchRequestRef]): Only the requests that matched in
            the run that emitted this record. A record is emitted once, on first
            sight, so a request that would match it in a later run never attaches to
            it.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "document": "document",
        "matched_requests": "matched_requests",
    }

    _optionals = [
        "document",
        "matched_requests",
    ]

    _nullables = [
        "document",
    ]

    def __init__(
        self,
        document=APIHelper.SKIP,
        matched_requests=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a SearchRecord instance."""
        # Initialize members of the class
        if document is not APIHelper.SKIP:
            self.document = document
        if matched_requests is not APIHelper.SKIP:
            self.matched_requests = matched_requests

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        if "document" in dictionary.keys():
            document =\
                Document.from_dictionary(
                dictionary.get("document"))\
                if dictionary.get("document") else None
        else:
            document = APIHelper.SKIP
        matched_requests = None
        if dictionary.get("matched_requests") is not None:
            matched_requests = [
                SearchRequestRef.from_dictionary(x)
                    for x in dictionary.get("matched_requests")
            ]
        else:
            matched_requests = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(document,
                   matched_requests,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _document=(
            self.document
            if hasattr(self, "document")
            else None
        )
        _matched_requests=(
            self.matched_requests
            if hasattr(self, "matched_requests")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"document={_document!r}, "
            f"matched_requests={_matched_requests!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _document=(
            self.document
            if hasattr(self, "document")
            else None
        )
        _matched_requests=(
            self.matched_requests
            if hasattr(self, "matched_requests")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"document={_document!s}, "
            f"matched_requests={_matched_requests!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
