"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.models.fields_2 import Fields2


class SearchRequest(object):
    """Implementation of the 'SearchRequest' model.

    Attributes:
        api_key (str): API key. On the HTTP surface, either this or the `x-api-key`
            header must be supplied; the header takes precedence.
        exclude_domains (List[str]): Exclude results from these domains
        fields (Fields2): The model property of type Fields2.
        from_date (str): Only include results published on or after this point. UTC
            throughout.  A date "2025-10-28", a datetime "2025-10-28T23:00:00" or
            "2025-10-28T23:00:00Z", or an offset from "now", which is the time the
            request is served: "now" itself, or "now-" and one duration such as
            "now-7d" for the past week. A datetime written without a zone is read as
            UTC, and a date written without a time is the start of that day.  Offset
            units are s = second, m = minute, h = hour, d = 24 h, w = 7 d, M = one
            calendar month and y = one calendar year. A unit and a count are both
            required, and the case carries meaning.  A month and a year step the
            calendar rather than a fixed number of seconds, and the day of the month
            is clamped to the length of the target month. So "now-1M" from the 31st
            of March lands on the 28th or 29th of February.  An offset is a filter,
            not a freshness guarantee: the corpus refreshes on its own cadence, so a
            window of an hour or two can return nothing.  Only a single offset before
            "now" is accepted. Rounding, several terms in one value, a "+" offset,
            and any anchor other than "now" are rejected.
        include_domains (List[str]): Include only results from these domains (e.g.,
            \["google.com", "example.com"\])
        max_results (int): Maximum number of results to return. Defaults to 10. A
            larger value is served as 1000.
        query (str): The search query.
        scope (str): Restricts the results to one vertical or data set.  Currently
            available: "news", "wikipedia", "people", "companies".  When omitted, the
            default scope is searched. A scope that does not exist, or that this key
            cannot reach, returns 404.
        tier (str): How much work goes into ordering the results. It does not change
            which corpus is searched -- that is `scope` -- so any scope can be
            requested in either tier.  `"base"` returns first-stage ranking. `"pro"`
            adds a ranking stage for higher precision at the top of the list.  Unset
            resolves to `"pro"`, so `"base"` is opt-out. A scope with no Pro
            configuration serves `"pro"` exactly as `"base"` rather than failing, so
            a caller may always ask for `"pro"`.  The name is matched without regard
            to case, and surrounding whitespace is ignored, so "pro", "PRO" and " Pro
            " are one tier. A name that is neither is rejected rather than defaulted,
            because the value selects a price.
        to_date (str): Only include results published on or before this point. UTC
            throughout.  A date, a datetime, or an offset from "now", in the same
            spellings from_date takes. A date written without a time covers the whole
            of that day, ending at 23:59:59.999; an offset is an instant.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "api_key": "api_key",
        "exclude_domains": "exclude_domains",
        "fields": "fields",
        "from_date": "from_date",
        "include_domains": "include_domains",
        "max_results": "max_results",
        "query": "query",
        "scope": "scope",
        "tier": "tier",
        "to_date": "to_date",
    }

    _optionals = [
        "api_key",
        "exclude_domains",
        "fields",
        "from_date",
        "include_domains",
        "max_results",
        "query",
        "scope",
        "tier",
        "to_date",
    ]

    _nullables = [
        "api_key",
        "fields",
        "from_date",
        "max_results",
        "scope",
        "tier",
        "to_date",
    ]

    def __init__(
        self,
        api_key=APIHelper.SKIP,
        exclude_domains=None,
        fields=APIHelper.SKIP,
        from_date=APIHelper.SKIP,
        include_domains=None,
        max_results=APIHelper.SKIP,
        query=APIHelper.SKIP,
        scope=APIHelper.SKIP,
        tier=APIHelper.SKIP,
        to_date=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a SearchRequest instance."""
        # Initialize members of the class
        if api_key is not APIHelper.SKIP:
            self.api_key = api_key
        self.exclude_domains = exclude_domains
        if fields is not APIHelper.SKIP:
            self.fields = fields
        if from_date is not APIHelper.SKIP:
            self.from_date = from_date
        self.include_domains = include_domains
        if max_results is not APIHelper.SKIP:
            self.max_results = max_results
        if query is not APIHelper.SKIP:
            self.query = query
        if scope is not APIHelper.SKIP:
            self.scope = scope
        if tier is not APIHelper.SKIP:
            self.tier = tier
        if to_date is not APIHelper.SKIP:
            self.to_date = to_date

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        api_key =\
            dictionary.get("api_key")\
            if "api_key" in dictionary.keys()\
                else APIHelper.SKIP
        exclude_domains =\
            dictionary.get("exclude_domains")\
            if dictionary.get("exclude_domains")\
                else None
        if "fields" in dictionary.keys():
            fields =\
                Fields2.from_dictionary(
                dictionary.get("fields"))\
                if dictionary.get("fields") else None
        else:
            fields = APIHelper.SKIP
        from_date =\
            dictionary.get("from_date")\
            if "from_date" in dictionary.keys()\
                else APIHelper.SKIP
        include_domains =\
            dictionary.get("include_domains")\
            if dictionary.get("include_domains")\
                else None
        max_results =\
            dictionary.get("max_results")\
            if "max_results" in dictionary.keys()\
                else APIHelper.SKIP
        query =\
            dictionary.get("query")\
            if dictionary.get("query")\
                else APIHelper.SKIP
        scope =\
            dictionary.get("scope")\
            if "scope" in dictionary.keys()\
                else APIHelper.SKIP
        tier =\
            dictionary.get("tier")\
            if "tier" in dictionary.keys()\
                else APIHelper.SKIP
        to_date =\
            dictionary.get("to_date")\
            if "to_date" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(api_key,
                   exclude_domains,
                   fields,
                   from_date,
                   include_domains,
                   max_results,
                   query,
                   scope,
                   tier,
                   to_date,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _api_key=(
            self.api_key
            if hasattr(self, "api_key")
            else None
        )
        _exclude_domains=(
            self.exclude_domains
            if hasattr(self, "exclude_domains")
            else None
        )
        _fields=(
            self.fields
            if hasattr(self, "fields")
            else None
        )
        _from_date=(
            self.from_date
            if hasattr(self, "from_date")
            else None
        )
        _include_domains=(
            self.include_domains
            if hasattr(self, "include_domains")
            else None
        )
        _max_results=(
            self.max_results
            if hasattr(self, "max_results")
            else None
        )
        _query=(
            self.query
            if hasattr(self, "query")
            else None
        )
        _scope=(
            self.scope
            if hasattr(self, "scope")
            else None
        )
        _tier=(
            self.tier
            if hasattr(self, "tier")
            else None
        )
        _to_date=(
            self.to_date
            if hasattr(self, "to_date")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"api_key={_api_key!r}, "
            f"exclude_domains={_exclude_domains!r}, "
            f"fields={_fields!r}, "
            f"from_date={_from_date!r}, "
            f"include_domains={_include_domains!r}, "
            f"max_results={_max_results!r}, "
            f"query={_query!r}, "
            f"scope={_scope!r}, "
            f"tier={_tier!r}, "
            f"to_date={_to_date!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _api_key=(
            self.api_key
            if hasattr(self, "api_key")
            else None
        )
        _exclude_domains=(
            self.exclude_domains
            if hasattr(self, "exclude_domains")
            else None
        )
        _fields=(
            self.fields
            if hasattr(self, "fields")
            else None
        )
        _from_date=(
            self.from_date
            if hasattr(self, "from_date")
            else None
        )
        _include_domains=(
            self.include_domains
            if hasattr(self, "include_domains")
            else None
        )
        _max_results=(
            self.max_results
            if hasattr(self, "max_results")
            else None
        )
        _query=(
            self.query
            if hasattr(self, "query")
            else None
        )
        _scope=(
            self.scope
            if hasattr(self, "scope")
            else None
        )
        _tier=(
            self.tier
            if hasattr(self, "tier")
            else None
        )
        _to_date=(
            self.to_date
            if hasattr(self, "to_date")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"api_key={_api_key!s}, "
            f"exclude_domains={_exclude_domains!s}, "
            f"fields={_fields!s}, "
            f"from_date={_from_date!s}, "
            f"include_domains={_include_domains!s}, "
            f"max_results={_max_results!s}, "
            f"query={_query!s}, "
            f"scope={_scope!s}, "
            f"tier={_tier!s}, "
            f"to_date={_to_date!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
