"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper


class SnippetOptions(object):
    """Implementation of the 'SnippetOptions' model.

    Tuning for snippet selection.
    Each option is an upper bound; the response carries at most what is specified
    here.
    The service may hold callers to a tighter bound than the ranges below. A larger
    request is then served at that bound rather than refused, which still carries at
    most what was specified. Only a value outside the range below is rejected.

    Attributes:
        max_snippets (int): Maximum snippets returned across all documents. Accepted
            range 1-512.  No default. Left unset, no response-wide ceiling applies at
            all, which is the recommended setting: `max_snippets_per_result` already
            bounds every document, so the response is bounded without one.  This
            budget is spent one snippet per document at a time, so every document
            gets its best snippet before any document gets a second. This value is
            potentially raised to ensure each document can be given at least one
            snippet.
        max_snippets_per_result (int): Maximum snippets from any single document.
            Defaults to 16, accepted range 1-256.
        max_tokens (int): Ceiling on tokens across all snippets in the response.
            Defaults to 8192, accepted range 512-65536.  Spent in the same order as
            `max_snippets`, one snippet per document at a time, but unlike
            `max_snippets` this ceiling is not raised to fit `max_results`. Set it
            low against many results and the budget runs out partway through a round:
            the documents it does not reach are still returned, with no snippets at
            all. If every result needs a snippet, raise this or lower `max_results`.
        max_tokens_per_result (int): Ceiling on tokens of snippets from any single
            document. Defaults to 4096, accepted range 128-32768.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "max_snippets": "max_snippets",
        "max_snippets_per_result": "max_snippets_per_result",
        "max_tokens": "max_tokens",
        "max_tokens_per_result": "max_tokens_per_result",
    }

    _optionals = [
        "max_snippets",
        "max_snippets_per_result",
        "max_tokens",
        "max_tokens_per_result",
    ]

    _nullables = [
        "max_snippets",
        "max_snippets_per_result",
        "max_tokens",
        "max_tokens_per_result",
    ]

    def __init__(
        self,
        max_snippets=APIHelper.SKIP,
        max_snippets_per_result=APIHelper.SKIP,
        max_tokens=APIHelper.SKIP,
        max_tokens_per_result=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a SnippetOptions instance."""
        # Initialize members of the class
        if max_snippets is not APIHelper.SKIP:
            self.max_snippets = max_snippets
        if max_snippets_per_result is not APIHelper.SKIP:
            self.max_snippets_per_result = max_snippets_per_result
        if max_tokens is not APIHelper.SKIP:
            self.max_tokens = max_tokens
        if max_tokens_per_result is not APIHelper.SKIP:
            self.max_tokens_per_result = max_tokens_per_result

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        max_snippets =\
            dictionary.get("max_snippets")\
            if "max_snippets" in dictionary.keys()\
                else APIHelper.SKIP
        max_snippets_per_result =\
            dictionary.get("max_snippets_per_result")\
            if "max_snippets_per_result" in dictionary.keys()\
                else APIHelper.SKIP
        max_tokens =\
            dictionary.get("max_tokens")\
            if "max_tokens" in dictionary.keys()\
                else APIHelper.SKIP
        max_tokens_per_result =\
            dictionary.get("max_tokens_per_result")\
            if "max_tokens_per_result" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(max_snippets,
                   max_snippets_per_result,
                   max_tokens,
                   max_tokens_per_result,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _max_snippets=(
            self.max_snippets
            if hasattr(self, "max_snippets")
            else None
        )
        _max_snippets_per_result=(
            self.max_snippets_per_result
            if hasattr(self, "max_snippets_per_result")
            else None
        )
        _max_tokens=(
            self.max_tokens
            if hasattr(self, "max_tokens")
            else None
        )
        _max_tokens_per_result=(
            self.max_tokens_per_result
            if hasattr(self, "max_tokens_per_result")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"max_snippets={_max_snippets!r}, "
            f"max_snippets_per_result={_max_snippets_per_result!r}, "
            f"max_tokens={_max_tokens!r}, "
            f"max_tokens_per_result={_max_tokens_per_result!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _max_snippets=(
            self.max_snippets
            if hasattr(self, "max_snippets")
            else None
        )
        _max_snippets_per_result=(
            self.max_snippets_per_result
            if hasattr(self, "max_snippets_per_result")
            else None
        )
        _max_tokens=(
            self.max_tokens
            if hasattr(self, "max_tokens")
            else None
        )
        _max_tokens_per_result=(
            self.max_tokens_per_result
            if hasattr(self, "max_tokens_per_result")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"max_snippets={_max_snippets!s}, "
            f"max_snippets_per_result={_max_snippets_per_result!s}, "
            f"max_tokens={_max_tokens!s}, "
            f"max_tokens_per_result={_max_tokens_per_result!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
