"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper


class Snippet(object):
    """Implementation of the 'Snippet' model.

    One passage selected from a document's body.

    Attributes:
        text (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "text": "text",
    }

    _optionals = [
        "text",
    ]

    _nullables = [
        "text",
    ]

    def __init__(
        self,
        text=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Snippet instance."""
        # Initialize members of the class
        if text is not APIHelper.SKIP:
            self.text = text

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        text =\
            dictionary.get("text")\
            if "text" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(text,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _text=(
            self.text
            if hasattr(self, "text")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"text={_text!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _text=(
            self.text
            if hasattr(self, "text")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"text={_text!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
