"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper


class Webhook1(object):
    """Implementation of the 'Webhook1' model.

    JSON `null` clears the webhook; an absent field keeps it. Set
    `webhook.status` to turn delivery on or off.

    Attributes:
        events (List[str]): Exactly two strings are legal: "run.completed" and
            "run.failed". An empty list is rejected.  "run.completed" means the run
            finished. Read the run's `record_count` to see whether it produced
            records and its `status` to see whether every request succeeded.
            "run.failed" means no request succeeded. Neither fires for a skipped run.
        status (str): Always reported on a monitor. Send ACTIVE to turn delivery back
            on once a failing endpoint is repaired, or DISABLED to stop it yourself.
            A disabled webhook stops the POST only. The monitor still runs and its
            records are still readable through the records cursor, so nothing is lost
            while it is off.  On the way in it is the one field of this message that
            may be omitted: an absent status keeps whatever the monitor already has,
            so re-sending a webhook body does not by itself restart delivery to a
            dead endpoint.
        url (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "events": "events",
        "status": "status",
        "url": "url",
    }

    _optionals = [
        "events",
        "status",
        "url",
    ]

    def __init__(
        self,
        events=None,
        status=APIHelper.SKIP,
        url=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Webhook1 instance."""
        # Initialize members of the class
        self.events = events
        if status is not APIHelper.SKIP:
            self.status = status
        if url is not APIHelper.SKIP:
            self.url = url

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        events =\
            dictionary.get("events")\
            if dictionary.get("events")\
                else None
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else APIHelper.SKIP
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(events,
                   status,
                   url,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _events=(
            self.events
            if hasattr(self, "events")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"events={_events!r}, "
            f"status={_status!r}, "
            f"url={_url!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _events=(
            self.events
            if hasattr(self, "events")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"events={_events!s}, "
            f"status={_status!s}, "
            f"url={_url!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
