"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from seltzapi.api_helper import APIHelper
from seltzapi.exceptions.api_exception import (
    ApiException,
)
from seltzapi.models.envelope_error_1 import (
    EnvelopeError1,
)


class ErrorEnvelopeException(ApiException):
    def __init__(self, reason, response):
        """Initialize ErrorEnvelopeException object.

        Args:
            reason (string): The reason (or error message) for the Exception
                to be raised.
            response (HttpResponse): The HttpResponse of the API call.

        """
        super(ErrorEnvelopeException, self).__init__(reason, response)
        dictionary = APIHelper.json_deserialize(self.response.text)
        if isinstance(dictionary, dict):
            self.unbox(dictionary)

    def unbox(self, dictionary):
        """Populate the properties of this object by extracting them from a dictionary.

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        """
        self.error =\
            EnvelopeError1.from_dictionary(
                dictionary.get("error"))\
                if dictionary.get("error") else None


    def __str__(self):
        """Return a human-readable string representation."""
        _error=self.error
        _base_str = super().__str__()
        _base_str = _base_str[_base_str.find("(") + 1:-1]
        return (
            f"{self.__class__.__name__}("
            f"base_str={_base_str!s}, "
            f"error={_error!s}, "
            f")"
        )
