"""seltzapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from apimatic_core.configurations.global_configuration import (
    GlobalConfiguration,
)
from apimatic_core.decorators.lazy_property import (
    LazyProperty,
)

from seltzapi.apis.agent_api import AgentApi
from seltzapi.apis.answer_api import AnswerApi
from seltzapi.apis.base_api import BaseApi
from seltzapi.apis.fetch_api import FetchApi
from seltzapi.apis.monitors_api import MonitorsApi
from seltzapi.apis.records_api import RecordsApi
from seltzapi.apis.runs_api import RunsApi
from seltzapi.apis.search_api import SearchApi
from seltzapi.configuration import (
    Configuration,
    Environment,
)
from seltzapi.http.auth.custom_header_authentication import (
    CustomHeaderAuthentication,
)


class SeltzapiClient(object):
    """Client that provide access to the SeltzapiClient APIs."""

    @LazyProperty
    def search(self):
        """Provide access to the SearchApi endpoints."""
        return SearchApi(self.global_configuration)

    @LazyProperty
    def answer(self):
        """Provide access to the AnswerApi endpoints."""
        return AnswerApi(self.global_configuration)

    @LazyProperty
    def monitors(self):
        """Provide access to the MonitorsApi endpoints."""
        return MonitorsApi(self.global_configuration)

    @LazyProperty
    def records(self):
        """Provide access to the RecordsApi endpoints."""
        return RecordsApi(self.global_configuration)

    @LazyProperty
    def runs(self):
        """Provide access to the RunsApi endpoints."""
        return RunsApi(self.global_configuration)

    @LazyProperty
    def agent(self):
        """Provide access to the AgentApi endpoints."""
        return AgentApi(self.global_configuration)

    @LazyProperty
    def fetch(self):
        """Provide access to the FetchApi endpoints."""
        return FetchApi(self.global_configuration)

    def __init__(self, http_client_instance=None,
                 override_http_client_configuration=False, http_call_back=None,
                 timeout=30, max_retries=0, backoff_factor=2,
                 retry_statuses=None, retry_methods=None, proxy_settings=None,
                 logging_configuration=None, environment=Environment.PRODUCTION,
                 custom_header_authentication_credentials=None, config=None):
        """Initialize a new instance of SeltzapiClient."""
        self.config = config or Configuration(
            http_client_instance=http_client_instance,
            override_http_client_configuration=override_http_client_configuration,
            http_call_back=http_call_back, timeout=timeout,
            max_retries=max_retries, backoff_factor=backoff_factor,
            retry_statuses=retry_statuses, retry_methods=retry_methods,
            proxy_settings=proxy_settings,
            logging_configuration=logging_configuration,
            environment=environment,
            custom_header_authentication_credentials=custom_header_authentication_credentials)

        self.global_configuration = GlobalConfiguration(self.config)\
            .global_errors(BaseApi.global_errors())\
            .base_uri_executor(self.config.get_base_uri)\
            .user_agent(BaseApi.user_agent(),
                BaseApi.user_agent_parameters())

        self.auth_managers = {
            "ApiKeyAuth": CustomHeaderAuthentication(
                self.config.custom_header_authentication_credentials),
        }
        self.global_configuration =\
            self.global_configuration.auth_managers(self.auth_managers)

    @classmethod
    def from_environment(cls, dotenv_path=None, **overrides):
        """Create a client instance using environment variables.

        Returns:
            SeltzapiClient instance.

        """
        return cls(config=Configuration
            .from_environment(dotenv_path=dotenv_path, **overrides))
